name: alfred_taxi_client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  geocoding: ^2.0.1
  geolocator: ^8.0.1
  flutter_svg: ^0.22.0
  map_picker:
  http: ^0.13.4
  equatable: ^2.0.3
  flutter_spinkit: ^5.1.0
  uuid: any
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1
  intl: ^0.17.0
  sizer: ^2.0.15
  rflutter_alert: ^2.0.4
  dropdown_search: ^2.0.1
  device_info: ^2.0.3
  platform_device_id: ^1.0.1
  get_storage: ^2.0.3
  url_launcher: ^6.0.17
  webview_flutter: ^3.0.0
  searchbar_animation: ^0.0.1
  material_floating_search_bar: ^0.3.6
  google_fonts: ^2.2.0
  modal_bottom_sheet: ^2.0.0
  font_awesome_flutter: ^9.2.0
  intl_phone_number_input: ^0.7.0+2
  google_maps_widget: ^1.0.1
  group_button: ^4.2.1
  count_stepper: ^0.0.4
  sms_autofill: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/json/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          # weight: 700

  uses-material-design: true
