name: alfred_taxi_driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: any
  #
  google_maps_flutter: ^2.1.0
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  geocoding: ^2.0.1
  geolocator: ^8.0.1
  #
  http: ^0.13.4

  flutter_spinkit: ^5.1.0
  uuid: any
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1
  intl: ^0.17.0
  sizer: ^2.0.15
  rflutter_alert: ^2.0.4
  dropdown_search: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  adaptive_dialog: ^1.2.0
  url_launcher: ^6.0.18
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  money_formatter: ^0.0.3
  google_maps_controller: ^1.2.0
  snapping_sheet: ^3.1.0
  stop_watch_timer: ^1.3.1
  intl_phone_field: ^3.0.1
  pinput: ^2.2.4
  otp_timer_button: ^1.1.0
  # flutter_contact: ^0.9.1+8
  permission_handler: ^9.2.0
  flutter_platform_widgets: ^1.20.0
  # sunny_dart: ^0.11.0+8
  # full_text_search: ^0.8.0+3
  webview_flutter_plus: ^0.3.0+2
  currency_formatter: ^1.2.0

  

  #

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/map_style.txt
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
  uses-material-design: true
