name: fredy_proprio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  auto_size_text: ^3.0.0
  sizer: ^2.0.15
  adaptive_dialog: ^1.3.0
  adaptive_theme: ^2.3.0
  bottom_bar: ^1.3.0+1
  get: 4.6.1
  get_storage: ^2.0.3
  uuid: any
  dropdown_plus: ^0.0.9
  awesome_dropdown: ^0.0.4
  modal_bottom_sheet: ^2.0.0
  image_picker_type: ^1.0.4
  settings_ui: ^2.0.2
  fl_chart: ^0.41.0
  intl: ^0.17.0
  syncfusion_flutter_datagrid: ^19.4.50
  syncfusion_flutter_charts: ^19.4.50
  intl_phone_field: ^3.0.1
  otp_text_field: ^1.1.2
  otp_timer_button: ^1.1.0
  url_launcher: ^6.0.18
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  flutter_contact: ^0.9.1+8
  permission_handler: ^9.2.0
  flutter_platform_widgets: ^1.20.0
  sunny_dart: ^0.11.0+8
  full_text_search: ^0.8.0+3
  webview_flutter_plus: ^0.3.0+2
  # flutter_masked_text2: ^0.9.1
  currency_formatter: ^1.2.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/json/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
  uses-material-design: true
